### ISSUE TITLE
Issue with azuremetadata

### ISSUE THREAD

**Issue by danigdp** [rfparedes/susecloud-repocheck#39]
Hi, I'm getting this error on Azure Suse 12 SP3:
Please provide a query option.2021-07-06 10:02:39,918 ERROR: PROBLEM: Issue with azuremetadata output. Check metadata access.

Could you help me?
Thx

**Comment by mikeislas06** [comment]
I am having the same issue. Please I need a possible answer for this

**Comment by rfparedes** [comment]
Sounds like the instance cannot contact the metadata service.  If the instance has an issue returning metadata with the following command "azuremetadata --api latest", then this is a problem with your configuration and not a bug.  If you still have an issue, open a new bug.
