### ISSUE TITLE
ERROR: Cannot get IP of RMT server entry.

### ISSUE THREAD

**Issue by RonnieWang2018** [rfparedes/susecloud-repocheck#40]
Hi,
I encountered SUSE register issue for ALL Azure SUSE VMs since last month. SUSE 15 and 12.
All SLES 15 VMs can auto resolved by run this repocheck.py.
But for SLES 12 VMs, the script is not working.
It showed ERROR: Cannot get IP of RMT server entry.

![image](https://user-images.githubusercontent.com/42931997/126421412-d54d50bc-7260-4514-8c0c-071f1844cbc0.png)

**Comment by rfparedes** [comment]
Wasn't getting notified of these bugs since July.  Sorry about that.  I'm closing and if you're still having an issue, open another bug and I will address it ASAP.
