### ISSUE TITLE
line 13 error

### ISSUE THREAD

**Issue by FoggyCheetah** [rfparedes/susecloud-repocheck#47]
I am getting the below error and can not seem to fix it, can you help

Traceback (most recent call last):
  File "/dev/fd/63", line 13, in <module>
ImportError: No module named 'requests'

**Comment by rfparedes** [comment]
Closing issue.  This looks related to your python setup as the requests module is not being found on that server.

**Comment by rfparedes** [comment]
What does the following return:

python3 -c "import requests"

Probably the same traceback?

If so, check to make sure python3-requests is installed:
rpm -qa | grep requests
python3-requests-.....

**Comment by FoggyCheetah** [comment]
yes I am getting this
rpm -qa | grep requests = python-requests-2.11.1-6.25.1.noarch
I also ran this
python --version = Python 2.7.13
I think you are saying I need at least version 3 of python, is
that correct?  If so, how can I update it?

**Comment by thimslugga** [comment]
@FoggyCheetah 

```
sudo zypper in -y python3 python3-requests
```

https://scc.suse.com/packages?name=SUSE%20Linux%20Enterprise%20Server&version=15.4&arch=x86_64&query=python3&module=2299

**Comment by FoggyCheetah** [comment]
This worked!  thank you
